name: Build Astro and deploy dist

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # match your project

      - name: Install dependencies
        run: npm ci

      - name: Build Astro project
        run: npm run build

      - name: Deploy dist to main-dist
        run: |
          # Configure Git
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Create temporary branch
          git checkout --orphan main-dist
          
          # Clean it
          git rm -rf .
          
          # Copy build output
          cp -r dist/* ./
          
          # Commit and force push
          git add .
          git commit -m "Update dist/ [skip ci]"
          git push origin temp-build:main-dist --force

