name: Build Astro and deploy dist

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22' # match your project

      - name: Install dependencies
        run: npm ci

      - name: Build Astro project
        run: npm run build

      # Optional: Commit built files (dist/) back to the same branch
      - name: Commit dist/
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dist/
          git commit -m "Update dist/ [skip ci]" || echo "No changes to commit"
          git push

